global.seeds = {
    mystical: {
        tier1: [
            { seed: 'mysticalagriculture:inferium_seeds',           result: 'mysticalagriculture:inferium_essence' },
            { seed: 'mysticalagriculture:stone_seeds',              result: 'mysticalagriculture:stone_essence' },
            { seed: 'mysticalagriculture:dirt_seeds',               result: 'mysticalagriculture:dirt_essence' },
            { seed: 'mysticalagriculture:wood_seeds',               result: 'mysticalagriculture:wood_essence' },
            { seed: 'mysticalagriculture:ice_seeds',                result: 'mysticalagriculture:ice_essence' },
            { seed: 'mysticalagriculture:deepslate_seeds',          result: 'mysticalagriculture:deepslate_essence' }

        ],
        tier2: [
            { seed: 'mysticalagriculture:nature_seeds',             result: 'mysticalagriculture:nature_essence' },
            { seed: 'mysticalagriculture:dye_seeds',                result: 'mysticalagriculture:dye_essence' },
            { seed: 'mysticalagriculture:nether_seeds',             result: 'mysticalagriculture:nether_essence' },
            { seed: 'mysticalagriculture:coal_seeds',               result: 'mysticalagriculture:coal_essence' },
            { seed: 'mysticalagriculture:coral_seeds',              result: 'mysticalagriculture:coral_essence' },
            { seed: 'mysticalagriculture:honey_seeds',              result: 'mysticalagriculture:honey_essence' },
            { seed: 'mysticalagriculture:amethyst_seeds',           result: 'mysticalagriculture:amethyst_essence' },
            { seed: 'mysticalagriculture:pig_seeds',                result: 'mysticalagriculture:pig_essence' },
            { seed: 'mysticalagriculture:chicken_seeds',            result: 'mysticalagriculture:chicken_essence' },
            { seed: 'mysticalagriculture:cow_seeds',                result: 'mysticalagriculture:cow_essence' },
            { seed: 'mysticalagriculture:sheep_seeds',              result: 'mysticalagriculture:sheep_essence' },
            { seed: 'mysticalagriculture:squid_seeds',              result: 'mysticalagriculture:squid_essence' },
            { seed: 'mysticalagriculture:fish_seeds',               result: 'mysticalagriculture:fish_essence' },
            { seed: 'mysticalagriculture:slime_seeds',              result: 'mysticalagriculture:slime_essence' },
            { seed: 'mysticalagriculture:turtle_seeds',             result: 'mysticalagriculture:turtle_essence' },
            { seed: 'mysticalagriculture:armadillo_seeds',          result: 'mysticalagriculture:armadillo_essence' },
            { seed: 'mysticalagriculture:rubber_seeds',             result: 'mysticalagriculture:rubber_essence' },
            { seed: 'mysticalagriculture:silicon_seeds',            result: 'mysticalagriculture:silicon_essence' },
            { seed: 'mysticalagriculture:sulfur_seeds',             result: 'mysticalagriculture:sulfur_essence' },
            { seed: 'mysticalagriculture:aluminum_seeds',           result: 'mysticalagriculture:aluminum_essence' },
            { seed: 'mysticalagriculture:saltpeter_seeds',          result: 'mysticalagriculture:saltpeter_essence' },
            { seed: 'mysticalagriculture:apatite_seeds',            result: 'mysticalagriculture:apatite_essence' },
            { seed: 'mysticalagriculture:grains_of_infinity_seeds', result: 'mysticalagriculture:grains_of_infinity_essence' }

        ],
        tier3: [
            { seed: 'mysticalagriculture:iron_seeds',               result: 'mysticalagriculture:iron_essence' },
            { seed: 'mysticalagriculture:copper_seeds',             result: 'mysticalagriculture:copper_essence' },
            { seed: 'mysticalagriculture:nether_quartz_seeds',      result: 'mysticalagriculture:nether_quartz_essence' },
            { seed: 'mysticalagriculture:glowstone_seeds',          result: 'mysticalagriculture:glowstone_essence' },
            { seed: 'mysticalagriculture:redstone_seeds',           result: 'mysticalagriculture:redstone_essence' },
            { seed: 'mysticalagriculture:obsidian_seeds',           result: 'mysticalagriculture:obsidian_essence' },
            { seed: 'mysticalagriculture:prismarine_seeds',         result: 'mysticalagriculture:prismarine_essence' },
            { seed: 'mysticalagriculture:zombie_seeds',             result: 'mysticalagriculture:zombie_essence' },
            { seed: 'mysticalagriculture:skeleton_seeds',           result: 'mysticalagriculture:skeleton_essence' },
            { seed: 'mysticalagriculture:creeper_seeds',            result: 'mysticalagriculture:creeper_essence' },
            { seed: 'mysticalagriculture:spider_seeds',             result: 'mysticalagriculture:spider_essence' },
            { seed: 'mysticalagriculture:phantom_seeds',            result: 'mysticalagriculture:phantom_essence' },
            { seed: 'mysticalagriculture:rabbit_seeds',             result: 'mysticalagriculture:rabbit_essence' },
            { seed: 'mysticalagriculture:tin_seeds',                result: 'mysticalagriculture:tin_essence' },
            { seed: 'mysticalagriculture:bronze_seeds',             result: 'mysticalagriculture:bronze_essence' },
            { seed: 'mysticalagriculture:zinc_seeds',               result: 'mysticalagriculture:zinc_essence' },
            { seed: 'mysticalagriculture:brass_seeds',              result: 'mysticalagriculture:brass_essence' },
            { seed: 'mysticalagriculture:silver_seeds',             result: 'mysticalagriculture:silver_essence' },
            { seed: 'mysticalagriculture:lead_seeds',               result: 'mysticalagriculture:lead_essence' },
            { seed: 'mysticalagriculture:graphite_seeds',           result: 'mysticalagriculture:graphite_essence' },
            { seed: 'mysticalagriculture:copper_alloy_seeds',       result: 'mysticalagriculture:copper_alloy_essence' },
            { seed: 'mysticalagriculture:redstone_alloy_seeds',     result: 'mysticalagriculture:redstone_alloy_essence' },
            { seed: 'mysticalagriculture:conductive_alloy_seeds',   result: 'mysticalagriculture:conductive_alloy_essence' },
            { seed: 'mysticalagriculture:steeleaf_seeds',           result: 'mysticalagriculture:steeleaf_essence' },
            { seed: 'mysticalagriculture:ironwood_seeds',           result: 'mysticalagriculture:ironwood_essence' },
            { seed: 'mysticalagriculture:sky_stone_seeds',          result: 'mysticalagriculture:sky_stone_essence' },
            { seed: 'mysticalagriculture:certus_quartz_seeds',      result: 'mysticalagriculture:certus_quartz_essence' }
        ],
        tier4: [
            { seed: 'mysticalagriculture:knightmetal_seeds',        result: 'mysticalagriculture:knightmetal_essence' },
            { seed: 'mysticalagriculture:fiery_ingot_seeds',        result: 'mysticalagriculture:fiery_ingot_essence' },
            { seed: 'mysticalagriculture:fluix_seeds',              result: 'mysticalagriculture:fluix_essence' },
            { seed: 'mysticalagriculture:energized_steel_seeds',    result: 'mysticalagriculture:energized_steel_essence' },
            { seed: 'mysticalagriculture:blazing_crystal_seeds',    result: 'mysticalagriculture:blazing_crystal_essence' },
            { seed: 'mysticalagriculture:gold_seeds',               result: 'mysticalagriculture:gold_essence' },
            { seed: 'mysticalagriculture:lapis_lazuli_seeds',       result: 'mysticalagriculture:lapis_lazuli_essence' },
            { seed: 'mysticalagriculture:end_seeds',                result: 'mysticalagriculture:end_essence' },
            { seed: 'mysticalagriculture:experience_seeds',         result: 'mysticalagriculture:experience_essence' },
            { seed: 'mysticalagriculture:breeze_seeds',             result: 'mysticalagriculture:breeze_essence' },
            { seed: 'mysticalagriculture:blaze_seeds',              result: 'mysticalagriculture:blaze_essence' },
            { seed: 'mysticalagriculture:ghast_seeds',              result: 'mysticalagriculture:ghast_essence' },
            { seed: 'mysticalagriculture:enderman_seeds',           result: 'mysticalagriculture:enderman_essence' },
            { seed: 'mysticalagriculture:steel_seeds',              result: 'mysticalagriculture:steel_essence' },
            { seed: 'mysticalagriculture:nickel_seeds',             result: 'mysticalagriculture:nickel_essence' },
            { seed: 'mysticalagriculture:constantan_seeds',         result: 'mysticalagriculture:constantan_essence' },
            { seed: 'mysticalagriculture:electrum_seeds',           result: 'mysticalagriculture:electrum_essence' },
            { seed: 'mysticalagriculture:invar_seeds',              result: 'mysticalagriculture:invar_essence' },
            { seed: 'mysticalagriculture:uranium_seeds',            result: 'mysticalagriculture:uranium_essence' },
            { seed: 'mysticalagriculture:ruby_seeds',               result: 'mysticalagriculture:ruby_essence' },
            { seed: 'mysticalagriculture:sapphire_seeds',           result: 'mysticalagriculture:sapphire_essence' },
            { seed: 'mysticalagriculture:peridot_seeds',            result: 'mysticalagriculture:peridot_essence' },
            { seed: 'mysticalagriculture:soulium_seeds',            result: 'mysticalagriculture:soulium_essence' },
            { seed: 'mysticalagriculture:hop_graphite_seeds',       result: 'mysticalagriculture:hop_graphite_essence' },
            { seed: 'mysticalagriculture:soularium_seeds',          result: 'mysticalagriculture:soularium_essence' },
            { seed: 'mysticalagriculture:dark_steel_seeds',         result: 'mysticalagriculture:dark_steel_essence' },
            { seed: 'mysticalagriculture:pulsating_alloy_seeds',    result: 'mysticalagriculture:pulsating_alloy_essence' },
            { seed: 'mysticalagriculture:energetic_alloy_seeds',    result: 'mysticalagriculture:energetic_alloy_essence' },
            { seed: 'mysticalagriculture:osmium_seeds',             result: 'mysticalagriculture:osmium_essence' },
            { seed: 'mysticalagriculture:fluorite_seeds',           result: 'mysticalagriculture:fluorite_essence' },
            { seed: 'mysticalagriculture:refined_glowstone_seeds',  result: 'mysticalagriculture:refined_glowstone_essence' },
            { seed: 'mysticalagriculture:refined_obsidian_seeds',   result: 'mysticalagriculture:refined_obsidian_essence' }
        ],
        tier5: [
            { seed: 'mysticalagriculture:diamond_seeds',            result: 'mysticalagriculture:diamond_essence' },
            { seed: 'mysticalagriculture:emerald_seeds',            result: 'mysticalagriculture:emerald_essence' },
            { seed: 'mysticalagriculture:netherite_seeds',          result: 'mysticalagriculture:netherite_essence' },
            { seed: 'mysticalagriculture:wither_skeleton_seeds',    result: 'mysticalagriculture:wither_skeleton_essence' },
            { seed: 'mysticalagriculture:platinum_seeds',           result: 'mysticalagriculture:platinum_essence' },
            { seed: 'mysticalagriculture:iridium_seeds',            result: 'mysticalagriculture:iridium_essence' },
            { seed: 'mysticalagriculture:vibrant_alloy_seeds',      result: 'mysticalagriculture:vibrant_alloy_essence' },
            { seed: 'mysticalagriculture:end_steel_seeds',          result: 'mysticalagriculture:end_steel_essence' },
            { seed: 'mysticalagriculture:yellorium_seeds',          result: 'mysticalagriculture:yellorium_essence' },
            { seed: 'mysticalagriculture:cyanite_seeds',            result: 'mysticalagriculture:cyanite_essence' },
            { seed: 'mysticalagriculture:spirited_crystal_seeds',   result: 'mysticalagriculture:spirited_crystal_essence' },
            { seed: 'mysticalagriculture:niotic_crystal_seeds',     result: 'mysticalagriculture:niotic_crystal_essence' },
            { seed: 'mysticalagriculture:uraninite_seeds',          result: 'mysticalagriculture:uraninite_essence' }
        ],
        tier6: [
            { seed: 'mysticalagriculture:nether_star_seeds',        result: 'mysticalagriculture:nether_star_essence' },
            { seed: 'mysticalagriculture:dragon_egg_seeds',         result: 'mysticalagriculture:dragon_egg_essence' },
            { seed: 'mysticalagriculture:nitro_crystal_seeds',      result: 'mysticalagriculture:nitro_crystal_essence' }
        ],
        elemental: [
            { seed:'mysticalagriculture:air_seeds',                 result:  'mysticalagriculture:air_essence'},
            { seed:'mysticalagriculture:earth_seeds',               result:  'mysticalagriculture:earth_essence'},
            { seed:'mysticalagriculture:water_seeds',               result:  'mysticalagriculture:water_essence'},
            { seed:'mysticalagriculture:fire_seeds',                result:  'mysticalagriculture:fire_essence'}
        ]
    },
    croptopia: [
        { seed: "croptopia:artichoke_seed",     crop: "croptopia:artichoke"},
        { seed: "croptopia:asparagus_seed",     crop: "croptopia:asparagus"},
        { seed: "croptopia:barley_seed",        crop: "croptopia:barley"},
        { seed: "croptopia:basil_seed",         crop: "croptopia:basil"},
        { seed: "croptopia:bellpepper_seed",    crop: "croptopia:bellpepper"},
        { seed: "croptopia:blackbean_seed",     crop: "croptopia:blackbean"},
        { seed: "croptopia:blackberry_seed",    crop: "croptopia:blackberry"},
        { seed: "croptopia:blueberry_seed",     crop: "croptopia:blueberry"},
        { seed: "croptopia:broccoli_seed",      crop: "croptopia:broccoli"},
        { seed: "croptopia:cabbage_seed",       crop: "croptopia:cabbage"},
        { seed: "croptopia:cantaloupe_seed",    crop: "croptopia:cantaloupe"},
        { seed: "croptopia:cauliflower_seed",   crop: "croptopia:cauliflower"},
        { seed: "croptopia:celery_seed",        crop: "croptopia:celery"},
        { seed: "croptopia:chile_pepper_seed",  crop: "croptopia:chile_pepper"},
        { seed: "croptopia:coffee_seed",        crop: "croptopia:coffee_beans"},
        { seed: "croptopia:corn_seed",          crop: "croptopia:corn"},
        { seed: "croptopia:cranberry_seed",     crop: "croptopia:cranberry"},
        { seed: "croptopia:cucumber_seed",      crop: "croptopia:cucumber"},
        { seed: "croptopia:currant_seed",       crop: "croptopia:currant"},
        { seed: "croptopia:eggplant_seed",      crop: "croptopia:eggplant"},
        { seed: "croptopia:elderberry_seed",    crop: "croptopia:elderberry"},
        { seed: "croptopia:garlic_seed",        crop: "croptopia:garlic"},
        { seed: "croptopia:ginger_seed",        crop: "croptopia:ginger"},
        { seed: "croptopia:grape_seed",         crop: "croptopia:grape"},
        { seed: "croptopia:greenbean_seed",     crop: "croptopia:greenbean"},
        { seed: "croptopia:greenonion_seed",    crop: "croptopia:greenonion"},
        { seed: "croptopia:honeydew_seed",      crop: "croptopia:honeydew"},
        { seed: "croptopia:hops_seed",          crop: "croptopia:hops"},
        { seed: "croptopia:kale_seed",          crop: "croptopia:kale"},
        { seed: "croptopia:kiwi_seed",          crop: "croptopia:kiwi"},
        { seed: "croptopia:leek_seed",          crop: "croptopia:leek"},
        { seed: "croptopia:lettuce_seed",       crop: "croptopia:lettuce"},
        { seed: "croptopia:mustard_seed",       crop: "croptopia:mustard"},
        { seed: "croptopia:oat_seed",           crop: "croptopia:oat"},
        { seed: "croptopia:olive_seed",         crop: "croptopia:olive"},
        { seed: "croptopia:onion_seed",         crop: "croptopia:onion"},
        { seed: "croptopia:peanut_seed",        crop: "croptopia:peanut"},
        { seed: "croptopia:pepper_seed",        crop: "croptopia:pepper"},
        { seed: "croptopia:pineapple_seed",     crop: "croptopia:pineapple"},
        { seed: "croptopia:radish_seed",        crop: "croptopia:radish"},
        { seed: "croptopia:raspberry_seed",     crop: "croptopia:raspberry"},
        { seed: "croptopia:rhubarb_seed",       crop: "croptopia:rhubarb"},
        { seed: "croptopia:rice_seed",          crop: "croptopia:rice"},
        { seed: "croptopia:rutabaga_seed",      crop: "croptopia:rutabaga"},
        { seed: "croptopia:saguaro_seed",       crop: "croptopia:saguaro"},
        { seed: "croptopia:soybean_seed",       crop: "croptopia:soybean"},
        { seed: "croptopia:spinach_seed",       crop: "croptopia:spinach"},
        { seed: "croptopia:squash_seed",        crop: "croptopia:squash"},
        { seed: "croptopia:strawberry_seed",    crop: "croptopia:strawberry"},
        { seed: "croptopia:sweetpotato_seed",   crop: "croptopia:sweetpotato"},
        { seed: "croptopia:tea_seed",           crop: "croptopia:tea_leaves"},
        { seed: "croptopia:tomatillo_seed",     crop: "croptopia:tomatillo"},
        { seed: "croptopia:tomato_seed",        crop: "croptopia:tomato"},
        { seed: "croptopia:turmeric_seed",      crop: "croptopia:turmeric"},
        { seed: "croptopia:turnip_seed",        crop: "croptopia:turnip"},
        { seed: "croptopia:vanilla_seeds",      crop: "croptopia:vanilla"},
        { seed: "croptopia:yam_seed",           crop: "croptopia:yam"},
        { seed: "croptopia:zucchini_seed",      crop: "croptopia:zucchini"},
        { seed: "minecraft:beetroot_seeds",     crop: "minecraft:beetroot"},
        { seed: "minecraft:melon_seeds",        crop: "minecraft:melon"},
        { seed: "minecraft:pumpkin_seeds",      crop: "minecraft:pumpkin"},
        { seed: "minecraft:torchflower_seeds",  crop: "minecraft:torchflower"},
        { seed: "minecraft:wheat_seeds",        crop: "minecraft:wheat"}
    ],
    other_mods: {
        aether: [
            {seed: "aether:berry_bush_stem",    result: "aether:blue_berry"},
            {seed: "aether:purple_flower",      result: "aether:purple_flower"},
            {seed: "aether:white_flower",       result: "aether:white_flower"},
        ],
    trees : {
        vanilla: [
            { sapling: 'minecraft:oak_sapling',      log: 'minecraft:oak_log' },
            { sapling: 'minecraft:spruce_sapling',   log: 'minecraft:spruce_log' },
            { sapling: 'minecraft:birch_sapling',    log: 'minecraft:birch_log' },
            { sapling: 'minecraft:jungle_sapling',   log: 'minecraft:jungle_log' },
            { sapling: 'minecraft:acacia_sapling',   log: 'minecraft:acacia_log' },
            { sapling: 'minecraft:dark_oak_sapling', log: 'minecraft:dark_oak_log' },
            { sapling: 'minecraft:cherry_sapling',   log: 'minecraft:cherry_log' }
        ],
        croptopia: [
            { sapling:'croptopia:fig_sapling',          result: 'croptopia:fig'},
            { sapling:'croptopia:dragonfruit_sapling',  result: 'croptopia:dragonfruit'},
            { sapling:'croptopia:date_sapling',         result: 'croptopia:date'},
            { sapling:'croptopia:coconut_sapling',      result: 'croptopia:coconut'},
            { sapling:'croptopia:cherry_sapling',       result: 'croptopia:cherry'},
            { sapling:'croptopia:cashew_sapling',       result: 'croptopia:cashew'},
            { sapling:'croptopia:banana_sapling',       result: 'croptopia:banana'},
            { sapling:'croptopia:avocado_sapling',      result: 'croptopia:avocado'},
            { sapling:'croptopia:apricot_sapling',      result: 'croptopia:apricot'},
            { sapling:'croptopia:cinnamon_sapling',     result: 'croptopia:cinnamon'},
            { sapling:'croptopia:walnut_sapling',       result: 'croptopia:walnut'},
            { sapling:'croptopia:starfruit_sapling',    result: 'croptopia:starfruit'},
            { sapling:'croptopia:plum_sapling',         result: 'croptopia:plum'},
            { sapling:'croptopia:persimmon_sapling',    result: 'croptopia:persimmon'},
            { sapling:'croptopia:pecan_sapling',        result: 'croptopia:pecan'},
            { sapling:'croptopia:pear_sapling',         result: 'croptopia:pear'},
            { sapling:'croptopia:peach_sapling',        result: 'croptopia:peach'},
            { sapling:'croptopia:orange_sapling',       result: 'croptopia:orange'},
            { sapling:'croptopia:nutmeg_sapling',       result: 'croptopia:nutmeg'},
            { sapling:'croptopia:nectarine_sapling',    result: 'croptopia:nectarine'},
            { sapling:'croptopia:mango_sapling',        result: 'croptopia:mango'},
            { sapling:'croptopia:lime_sapling',         result: 'croptopia:lime'},
            { sapling:'croptopia:lemon_sapling',        result: 'croptopia:lemon'},
            { sapling:'croptopia:kumquat_sapling',      result: 'croptopia:kumquat'},
            { sapling:'croptopia:grapefruit_sapling',   result: 'croptopia:grapefruit'},
            { sapling:'croptopia:apple_sapling',        result: 'minecraft:apple'},
            { sapling:'croptopia:almond_sapling',       result: 'croptopia:almond'}
        ],
        arsNoveau: [
           { sapling: 'ars_nouveau:blue_archwood_sapling',   result: 'ars_nouveau:blue_archwood_log'},
           { sapling: 'ars_nouveau:red_archwood_sapling',    result: 'ars_nouveau:red_archwood_log'},
           { sapling: 'ars_nouveau:purple_archwood_sapling', result: 'ars_nouveau:purple_archwood_log'},
           { sapling: 'ars_nouveau:green_archwood_sapling',  result: 'ars_nouveau:green_archwood_log'}
        ],
        twillight: [
            { sapling:'twilightforest:rainbow_oak_sapling',     result: { main: 'twilightforest:twilight_oak_log',  second: 'twilightforest:rainbow_oak_leaves' } },
            { sapling:'twilightforest:canopy_sapling',          result: { main: 'twilightforest:canopy_log',        second: 'twilightforest:firefly' } },
            { sapling:'twilightforest:twilight_oak_sapling',    result: { main: 'twilightforest:twilight_oak_log',  second: 'twilightforest:firefly' } },
            { sapling:'twilightforest:mangrove_sapling',        result: { main: 'twilightforest:mangrove_log',      second: 'twilightforest:firefly' } },
            { sapling:'twilightforest:sorting_sapling',         result: { main: 'twilightforest:sorting_log',       second: 'twilightforest:sorting_log_core' } },
            { sapling:'twilightforest:mining_sapling',          result: { main: 'twilightforest:mining_log',        second: 'twilightforest:mining_log_core' } },
            { sapling:'twilightforest:transformation_sapling',  result: { main: 'twilightforest:transformation_log',second: 'twilightforest:transformation_log_core' } },
            { sapling:'twilightforest:time_sapling',            result: { main: 'twilightforest:time_log',          second: 'twilightforest:firefly' } },
            { sapling:'twilightforest:darkwood_sapling',        result: { main: 'twilightforest:dark_log',          second: 'twilightforest:firefly' } },
            { sapling:'twilightforest:hollow_oak_sapling',      result: { main: 'twilightforest:twilight_oak_log',  second: 'twilightforest:cicada' } }
        ],
        aether: [
            { sapling:'aether:skyroot_sapling',     result: { main: 'aether:skyroot_log',  second: 'aether:skyroot_log' } },
            { sapling:'aether:golden_oak_sapling',  result: { main: 'aether:skyroot_log',  second: 'aether:golden_oak_log' } },

        ]
    }
}