// priority: 0

let hide_ores = (event, active, debug) => {
    if(!active) return;

    let remove_ore = [
        "immersiveengineering:deepslate_ore_aluminum",
        "immersiveengineering:deepslate_ore_lead",
        "immersiveengineering:deepslate_ore_nickel",
        "immersiveengineering:deepslate_ore_silver",
        "immersiveengineering:deepslate_ore_uranium",
        "immersiveengineering:dust_aluminum",
        "immersiveengineering:dust_constantan",
        "immersiveengineering:dust_copper",
        "immersiveengineering:dust_electrum",
        "immersiveengineering:dust_gold",
        "immersiveengineering:dust_iron",
        "immersiveengineering:dust_lead",
        "immersiveengineering:dust_nickel",
        "immersiveengineering:dust_silver",
        "immersiveengineering:dust_steel",
        "immersiveengineering:dust_uranium",
        "immersiveengineering:ingot_aluminum",
        "immersiveengineering:ingot_constantan",
        "immersiveengineering:ingot_electrum",
        "immersiveengineering:ingot_lead",
        "immersiveengineering:ingot_nickel",
        "immersiveengineering:ingot_silver",
        "immersiveengineering:ingot_steel",
        "immersiveengineering:ingot_uranium",
        "immersiveengineering:nugget_aluminum",
        "immersiveengineering:nugget_constantan",
        "immersiveengineering:nugget_electrum",
        "immersiveengineering:nugget_lead",
        "immersiveengineering:nugget_nickel",
        "immersiveengineering:nugget_silver",
        "immersiveengineering:nugget_steel",
        "immersiveengineering:nugget_uranium",
        "immersiveengineering:ore_aluminum",
        "immersiveengineering:ore_lead",
        "immersiveengineering:ore_nickel",
        "immersiveengineering:ore_silver",
        "immersiveengineering:ore_uranium",
        "immersiveengineering:plate_aluminum",
        "immersiveengineering:plate_constantan",
        "immersiveengineering:plate_copper",
        "immersiveengineering:plate_electrum",
        "immersiveengineering:plate_gold",
        "immersiveengineering:plate_iron",
        "immersiveengineering:plate_lead",
        "immersiveengineering:plate_nickel",
        "immersiveengineering:plate_silver",
        "immersiveengineering:plate_steel",
        "immersiveengineering:plate_uranium",
        "immersiveengineering:raw_aluminum",
        "immersiveengineering:raw_block_aluminum",
        "immersiveengineering:raw_block_lead",
        "immersiveengineering:raw_block_nickel",
        "immersiveengineering:raw_block_silver",
        "immersiveengineering:raw_block_uranium",
        "immersiveengineering:raw_lead",
        "immersiveengineering:raw_nickel",
        "immersiveengineering:raw_silver",
        "immersiveengineering:raw_uranium",
        "immersiveengineering:storage_aluminum",
        "immersiveengineering:storage_constantan",
        "immersiveengineering:storage_electrum",
        "immersiveengineering:storage_lead",
        "immersiveengineering:storage_nickel",
        "immersiveengineering:storage_silver",
        "immersiveengineering:storage_steel",
        "immersiveengineering:storage_uranium"
    ]

    remove_ore.forEach(element => {
        event.hide(element)
    });

};